### ISSUE TITLE
Screen size issues

### ISSUE THREAD

**Issue by jb624-unikent** [unikent/moodle-theme_kent#111]
Page width for viewport between 840px to 1280px wide is way too narrow, possibly caused by: https://github.com/unikent/moodle-theme_kent/commit/d87bd577911e83a9489d7ae866b70cf54b3f41a3

Offending rule:
@media (min-width: 768px)
.container {
width: 730px;
}

Suggest setting auto width between 768 to 1280 media queries

**Comment by sk-unikent** [comment]
https://github.com/BenWhitehead/bootstrap-big-grid/blob/master/less/grid.less
